language: node_js
node_js:
  - "9.2.0"
sudo: false
cache:
  directories:
    - node_modules
script:
  - "npm test"
after_success:
  - "npm run coveralls"
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
